export const SKILLS = [
  { name: "Python", link: "https://www.python.org/" },
  { name: "Groovy", link: "http://www.groovy-lang.org/" },
  { name: "Bash", link: "https://www.gnu.org/software/bash/" },
  {
    name: "Powershell",
    link: "https://learn.microsoft.com/en-us/powershell/scripting/gallery/overview?view=powershell-7.4",
  },
  {
    name: "JavaScript",
    link: "https://developer.mozilla.org/en-US/docs/Web/javascript",
  },
  { name: "AWS", link: "https://aws.amazon.com/" },
  { name: "GCP", link: "https://console.cloud.google.com/" },
  { name: "Terraform", link: "https://www.terraform.io/" },
  { name: "Consul", link: "https://www.consul.io/" },
  { name: "Packer", link: "https://www.packer.io/" },
  {
    name: "Ansible",
    link: "https://docs.ansible.com/ansible/latest/getting_started/index.html",
  },
  { name: "Kubernetes", link: "https://kubernetes.io/" },
  { name: "Docker", link: "https://www.docker.com/" },
  { name: "Nginx", link: "https://nginx.org/en/" },
  { name: "Jenkins", link: "https://www.jenkins.io/" },
  { name: "Github Actions", link: "https://docs.github.com/en/actions" },
  { name: "ElasticSearch", link: "https://www.elastic.co/elasticsearch" },
  { name: "Beats", link: "https://www.elastic.co/beats" },
  { name: "Sensu", link: "https://sensu.io/" },
  { name: "Selenium", link: "https://www.selenium.dev/" },
  { name: "Playwright", link: "https://playwright.dev/" },
  {
    name: "Azure DevOps",
    link: "https://azure.microsoft.com/en-us/products/devops/",
  },
]
