---
- name: Get worker node join
  ansible.builtin.shell:
    cmd: microk8s add-node | grep worker
  register: worker_join
  when: "group_names[0] == 'controller-node'"

- ansible.builtin.debug:
    var: hostvars[groups['controller-node'][0]]['worker_join']['stdout_lines'][-1]

- ansible.builtin.set_fact:
    worker_join_cmd: "{{ hostvars[groups['controller-node'][0]]['worker_join']['stdout_lines'][-1] }}"
  
- name: Skip if already joined
  ansible.builtin.shell:
    cmd: |
      microk8s kubectl get nodes | grep {{ groups['worker-node'][0] }}
  when: "group_names[0] == 'controller-node'"
  register: worker_joined
    
- name: Join cluster as worker node
  ansible.builtin.shell:
    cmd: |
      {{ worker_join_cmd }} --worker
  when: 
    - hostvars[groups['controller-node'][0]]['worker_join']['rc'] != 0 
    - "group_names[0] == 'worker-node'"