name: Get build manifest

on: 
  workflow_call:
    outputs:
      build-site: 
        value: ${{ jobs.set-build-manifest.outputs.build-site }}
      build-mail-service: 
        value: ${{ jobs.set-build-manifest.outputs.build-mail-service }}
      changes: 
        value: ${{ jobs.set-build-manifest.outputs.changes }}
      images: 
        value: ${{ jobs.set-build-manifest.outputs.images }}

jobs:
  set-build-manifest:
    runs-on: ubuntu-latest
    outputs:
      build-site: ${{ steps.changes.outputs.site }}
      build-mail-service: ${{ steps.changes.outputs.mail-service }}
      images: ${{ steps.changes.outputs.images }}
    steps:
      - uses: actions/checkout@v4

      - name: Get updated files
        uses: dorny/paths-filter@v3
        id: images
        with:
          filters: |
            site:
              - ['src/**', 'content/**', 'docker/site/**', '*.js', 'package.json', 'package-lock.json']
            mail-service:
              - 'docker/mail-service/**'
    
            