name: Build docker image and push to GCP Artifact Registry

on: 
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      tag:
        required: true
        type: string
      dockerfile:
        required: true
        type: string

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentals_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: GCP Docker regstiry auth
        run: |
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet
      
      - name: Build image
        run: |
          docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/${{ inputs.image-name }}:${{ inputs.tag }} -f ${{ inputs.dockerfile }} .
          docker image tag ${{ secrets.ARTIFACT_REGISTRY }}/${{ inputs.image-name }}:${{ inputs.tag }} \
            ${{ secrets.ARTIFACT_REGISTRY }}/${{ inputs.image-name }}:latest
      
      - name: Push image
        run: |
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/${{ inputs.image-name }}:${{ inputs.tag }}
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/${{ inputs.image-name }}:latest

