name: Build docker image and push to GCP Artifact Registry

on: 
  workflow_call:
    inputs:
      images:
        required: false
        type: string
        default: '[""]'
        
jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: ${{ fromJson(inputs.images) }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Set docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.ref_name == 'main' && secrets.ARTIFACT_REGISTRY || '' }}${{ matrix.image }}
          tags:
            type=raw,v${{ github.run_number }}
            type=raw,value=latest
          labels:
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Login to GAR
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.image }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan image with trivy
        if: ${{ github.event_name == 'pull_request' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.image }}:latest
          format: 'sarif'
          output: 'trivy-results.sarif'
          timeout: 20m0s

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() &&  github.event_name == 'pull_request' }}
        with:
          sarif_file: 'trivy-results.sarif'

