name: PR Check workflow

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write
  checks: write
  security-events: write
  contents: read

jobs:
  set-build-manifest:
    uses: ./.github/workflows/build-manifest.yml

  docker-check:
    needs: set-build-manifest
    uses: ./.github/workflows/build-image.yml
    if: ${{ fromJson(needs.set-build-manifest.outputs.images) != 'false' }}
    with:
      images: ${{ needs.set-build-manifest.outputs.images }}
