name: PR Check workflow

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write
  checks: write
  security-events: write

jobs:
  set-build-manifest:
    uses: ./.github/workflows/build-manifest.yml

  docker-check:
    needs: set-build-manifest
    uses: ./.github/workflows/build-image.yml
    if: ${{ needs.set-build-manifest.outputs.images != 'false' }}
    with:
      images: ${{ needs.set-build-manifest.outputs.images }}

  tfsec-scan:
    runs-on: ubuntu-latest
    needs: set-build-manifest
    if: ${{ contains(needs.set-build-manifest.outputs.changes, 'deploy') }}
    steps:
      - uses: actions/checkout@v4

      - name: Run scan on GCP deployment
        if: ${{ needs.set-build-manifest.outputs.deploy-site-resources == 'true' }}
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: terraform/modules/site-resources

      - name: Run scan on K8s deployment
        if: ${{ needs.set-build-manifest.outputs.deploy-k8s-resources == 'true' }}
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: terraform/modules/k8s-resources

  terraform-plan:
    runs-on: ubuntu-latest
    needs: set-build-manifest
    if: ${{ contains(needs.set-build-manifest.outputs.changes, 'deploy') }}
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
    
      - name: GCP site resources plan
        if: ${{ needs.set-build-manifest.outputs.deploy-site-resources == 'true' }}
        uses: dflook/terraform-plan@v1
        with:
          path: terraform/modules/site-resources
          label: GCP site resources plan
          variables: |
              project_id      = "${{ secrets.PROJECT_ID }}"
              region          = "${{ secrets.REGION }}"
              zone            = "${{ secrets.ZONE }}"
              subnetwork_cidr = "${{ secrets.SUBNET_CIDR }}"
              pods_cidr       = "${{ secrets.PODS_CIDR }}"
              services_cidr   = "${{ secrets.SERVICES_CIDR }}"

      - name: K8s resources plan
        if: ${{ needs.set-build-manifest.outputs.deploy-k8s-resources == 'true' }}
        uses: dflook/terraform-plan@v1
        with:
          path: terraform/modules/k8s-resources
          label: K8s resources plan
          variables: |
              project_id      = "${{ secrets.PROJECT_ID }}"
              region          = "${{ secrets.REGION }}"